# @package _group_
hydra:
  run:
    dir: .

common:
  log_format: tqdm
  log_interval: 5
  # wandb_project: ignisight

checkpoint:
  save_dir: outputs/temp_fix/test01

task:
  _name: temp_fix

dataset:
  num_workers: 0
  batch_size: 4

criterion:
  _name: temp_fix

optimization:
  max_epoch: 20
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: fixed

model:
  _name: base_unet
  base_layers: 6

distributed_training:
  distributed_world_size: 1
  ddp_backend: no_c10d
